version: "3.9"

# Networks
networks:
  laravel-network:
    driver: bridge

# Volumes
volumes:
  laravel-postgres-data:
  laravel-mongodb-data:
  laravel-redis-data:
  laravel-rabbitmq-data:

# Nodes
services:
  # PHP-fpm Service
  laravel-app:
    build:
      context: ./docker-containers/app
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    ports:
      - ${APP_SUPERVISOR_PORT}:9001
    working_dir: /var/www/laravel
    volumes:
      - ./src/laravel:/var/www/laravel:cached
      - ./docker-containers/app/horizon.conf:/etc/supervisor/conf.d/horizon.conf
      - ./docker-containers/app/fpm.conf:/etc/supervisor/fpm.conf
      - ./docker-containers/app/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker-containers/nginx/letsencrypt:/etc/letsencrypt
    links:
      - laravel-postgres
      - laravel-redis
      - laravel-memcached
      - laravel-mongodb
    networks:
      - laravel-network

  # Nginx Service
  laravel-nginx:
    build:
      context: ./docker-containers/nginx
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - ${WEBSERVER_HTTP_PORT}:80
      - ${WEBSERVER_HTTPS_PORT}:443
    volumes:
      - ./src/laravel:/var/www/laravel:cached
      - ./docker-containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-containers/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-containers/nginx/letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
    links:
      - laravel-socket
      - laravel-app
    networks:
      - laravel-network

  # Laravel Echo Server
  laravel-socket:
    build:
      context: ./docker-containers/laravel-echo-server
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: laravel-socket
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-containers/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
      - ./docker-containers/nginx/letsencrypt:/etc/letsencrypt
    ports:
      - ${APP_WEBSOCKET_PORT}:6001
    links:
      - laravel-redis
    networks:
      - laravel-network

  # PostgreSQL
  laravel-postgres:
    build:
      context: ./docker-containers/postgres
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: laravel-postgres
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - laravel-postgres-data:/var/lib/postgresql/data:rw
    #    - ./docker-containers/postgres/postgres.conf:/var/lib/postgresql/data/postgres.conf
    command: postgres -c shared_buffers=512MB -c effective_cache_size=1536MB -c work_mem=2621kB -c maintenance_work_mem=128MB
    networks:
      - laravel-network

  # ClickHouse
  laravel-clickhouse:
    container_name: laravel-clickhouse
    build:
      context: ./docker-containers/clickhouse
      args:
        TIMEZONE: ${TIMEZONE}
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      TZ: ${TIMEZONE}
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./volumes/clickhouse-data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ports:
      - ${CLICKHOUSE_PORT}:8123
    networks:
      - laravel-network

  # Memcached
  laravel-memcached:
    build:
      context: ./docker-containers/memcached
    container_name: laravel-memcached
    restart: always
    environment:
      MEMCACHED_CACHE_SIZE: ${MEMCACHED_CACHE_SIZE}
    networks:
      - laravel-network

  # Redis
  laravel-redis:
    build:
      context: ./docker-containers/redis
    container_name: laravel-redis
    restart: unless-stopped
    command:
      - 'redis-server'
      - '--include /etc/redis/redis.conf'
      - '--loglevel ${REDIS_LOGLEVEL:-notice}'
      #      - '--logfile /var/log/redis-error.log'
      - '--maxmemory ${REDIS_MAXMEM:-1gb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass ${REDIS_PASS:-root}'
      - '--port ${REDIS_PORT:-6379}'
    volumes:
      - ./docker-containers/redis/redis.conf:/etc/redis/redis.conf
      - laravel-redis-data:/data
    #      - ./logs:/var/log/redis
    networks:
      - laravel-network

  # MongoDB
  laravel-mongodb:
    build:
      context: ./docker-containers/mongodb
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: laravel-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - laravel-mongodb-data:/data/db
      - ./docker-containers/mongodb/build:/build
    logging:
      driver: none
    networks:
      - laravel-network
    command: --storageEngine wiredTiger --auth --wiredTigerCacheSizeGB 0.5 --wiredTigerMaxCacheOverflowFileSizeGB 0.5

  # RabbitMQ
  laravel-rabbitmq:
      build:
        context: ./docker-containers/rabbitmq
        args:
          TIMEZONE: ${TIMEZONE}
      container_name: laravel-rabbitmq
      restart: unless-stopped
      environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
#        RABBITMQ_SSL_CACERTFILE: ${RABBITMQ_SSL_CACERTFILE}
#        RABBITMQ_SSL_CERTFILE: ${RABBITMQ_SSL_CERTFILE}
#        RABBITMQ_SSL_KEYFILE: ${RABBITMQ_SSL_KEYFILE}
#        RABBITMQ_SSL_VERIFY: ${RABBITMQ_SSL_VERIFY}
#        RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: ${RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT}
      ports:
          - ${RABBITMQ_MANAGEMENT_PORT}:15672
      volumes:
          - laravel-rabbitmq-data:/var/lib/rabbitmq
#          - ./docker-containers/rabbitmq/rootCA.pem:/rootCA.pem"
#          - ./docker-containers/rabbitmq/rootCA.key:/rootCA.key"
      networks:
      - laravel-network

  # Adminer
  laravel-adminer:
    build:
      context: ./docker-containers/adminer
    container_name: laravel-adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT}:8080
    logging:
      driver: none
    networks:
      - laravel-network

  # RoadRunner service
  laravel-roadrunner:
    build:
      context: ./docker-containers/roadrunner
      args:
        TIMEZONE: ${TIMEZONE}
        RR_VERSION: ${RR_VERSION}
    container_name: laravel-roadrunner
    restart: unless-stopped
    ports:
      - ${ROADRUNNER_HTTP_PORT}:8082
      - ${ROADRUNNER_HTTPS_PORT}:8084
      - ${ROADRUNNER_HEALTH_PORT}:8085
      - ${ROADRUNNER_METRICS_POST}:8086
    volumes:
      - ./src/roadrunner/:/var/www/roadrunner
      - ./docker-containers/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - laravel-network

