name: Laravel

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        stability: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: (cd ./src/laravel && composer validate)

      - name: Syntax check only (lint)
        run: find ./src/laravel -name "*.php" -print0 | xargs -0 -n1 -P8 php -l

      - name: Copy .env
        run: (cd ./src/laravel && composer run-script post-root-package-install)
      
      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: (cd ./src/laravel && composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --no-scripts)
 
      - name: Generate key
        run: (cd ./src/laravel && php artisan key:generate --force)
      
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: (cd ./src/laravel && php artisan test)