name: Telegram Notify

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  telegram-notify:
    name: Telegram Notify

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Send telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered
          message: |
            The ${{ github.event_name }} event triggered
            echo This event is a pull request.